### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by kensupermen** [kensupermen/stock_chart#8]
Add docker config

**Comment by andrefreitas** [comment]
Hi, I would like to take this issue. Can you make the goals more clear?

My suggestions are:
1. Create a Dockerfile to build a Docker image to deploy stock_chart
2. Create a docker-compose for speeding up development

**Comment by kensupermen** [comment]
Hi @andrefreitas, 
I'm done in this pr: https://github.com/kensupermen/stock_chart/pull/14
But, I can't cache gems to speed up docker-compose up. Do you know how to do that?

**Comment by andrefreitas** [comment]
@kensupermen I have added some comments of issues I have found in your Dockerfile to achieve Gems Cache.

**Comment by kensupermen** [comment]
Hi @andrefreitas 
Thanks so much
